# Copilot Coding Agent Setup Steps
# This workflow configures the environment for GitHub Copilot coding agents
# (Claude, Codex, etc.) to autonomously work on issues and PRs.

name: "Copilot Setup Steps"

on: workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install validation tools
      - name: Install HTML validation tools
        run: npm install -g htmlhint

      # Validate all HTML pages
      - name: Validate HTML files
        run: |
          echo "=== Validating index.html ==="
          htmlhint index.html || true
          echo ""
          echo "=== Validating demo.html ==="
          htmlhint demo.html || true
          echo ""
          echo "=== Validating analysis.html ==="
          htmlhint analysis.html || true

      # Show project structure and key file info
      - name: Project overview
        run: |
          echo "=== Project Structure ==="
          find . -not -path './.git/*' -type f | sort
          echo ""
          echo "=== HTML file sizes ==="
          wc -l index.html demo.html analysis.html
          echo ""
          echo "=== Dockerfile check ==="
          cat Dockerfile
          echo ""
          echo "=== GitHub workflows ==="
          ls -la .github/workflows/

      # Verify Docker build works
      - name: Verify Docker build
        run: |
          docker build -t gif-captcha-test .
          echo "Docker build successful"
