name: 💡 Feature Request
description: Suggest a new feature or research direction for GIF CAPTCHA
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to improve the case study or explore a new research direction? We'd love to hear it!

  - type: textarea
    id: problem
    attributes:
      label: Problem or Motivation
      description: What problem does this feature solve, or what research question does it address?
      placeholder: I noticed that the study doesn't cover...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you implement or approach this?
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Research methodology
        - New model benchmarking
        - Demo UI/UX improvement
        - GIF test set expansion
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative approaches you've thought about?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, references, or screenshots.
